src_dir: src
out_dir: out
clear_ouput: True
dump: dump
global_args: {}
exclude_render:
- component/
- content/
- heste/
- .*\.py
post_build: |
  from os import system
  from pathlib import Path
  for file in Path("static").iterdir():
    cmd = f"ln -srf static/{file.name} out/{file.name}"
    print(cmd)
    system(cmd)