[
	["Hyg med hest Hold u. 7 år", "400kr", "40 minutter (fra august 2024)", "Fast månedspris 10 måneder pr. år"],
	["Gå til hest for børn-hold 7-10 år", "550kr", "60 minutter (fra august 2024)", "Fast månedspris, forældre skal hjælpe. 10 måneder om året."],
	["Introhold fra 10 år", "550kr", "60 minutter", "Fast månedspris 10 mdr. hvert år"],
	["Basishold fra 10 år", "600kr", "60 minutter", "Fast månedspris 10 mdr. hvert år"],
	["Nørdehold", "750kr", "90 minutter", "Fast månedspris 10 mdr. hvert år"],
	["Spring og bomtræning hold", "200kr el. 1 klip", "60 minutter", "Pr. gang. Fast lektionspris april, maj, juni, august, september, oktober. Kun for ryttere på partordning, basis eller nørde hold eller ryttere med egen hest"],
	["Teorihold", "300kr", "60 minutter", "Fast månedspris januar, februar, marts, oktober, november. Enkelt gang 100 kr."],
	["Jordtræning og agility fra jord", "300kr", "", "Fast månedspris. Enkeltgang 100 kr."],
	["Rideterapi børn", "450kr", "45 minutter", ""],
	["Rideterapi/samtaleterapi voksen ", "600kr", "60 minutter", ""],
	["Eneundervisning", "400kr", "45 minutter", "Pr. gang evt. + kørepenge, kan deles af flere"],
	["Ene undervisning", "300kr", "30 minutter", "Pr. gang evt. + kørepenge, kan deles af flere"],
	["Onsdagspart", "400kr", "Part med hjælp 12 måneder om året", "Forudsætter hold eller månedlig eneundervisning"],
	["Weekendpart 1", "500kr", "Part en weekenddag 8-13 ", "12 måneder pr. år"],
	["Weekendpart 2", "900kr", "Part to weekenddage 8-13", "12 måneder pr. år"],
	["Distancepart til de lange klasser", "1200kr", "3 dage om ugen. Inkl. træningsplan til MA distance", "12 måneder pr. år"],
	["Løs Lektion ", "200kr el. 1 klip", "På hold hvor der er plads", ""],
	["Fri part dag", "200kr el. 1 klip", "Enkelt partdag efter aftale", ""],
	["Klippekort Lille", "900 kr", "5 klip", ""],
	["Klippekort Stor", "1700kr", "10 klip", ""],
	["Hest i træning", "6500kr", "Pr. måned inkl. boks, bund, fold og stråfoder ", ""],
]

