src_dir: src
out_dir: ../public_html
clear_output: True
global_args: {}
exclude_render:
- component/
- content/
- heste/
- nav/
- .*\.py
post_build: |
  from os import system
  from pathlib import Path
  for file in Path("static").iterdir():
    cmd = f"ln -srf static/{file.name} ../public_html/{file.name}"
    print(cmd)
    system(cmd)