src_dir: src
out_dir: ../public_html
clear_output: True
global_args: {}
exclude_render:
- component/
- content/
- heste/
- nav/
- .*\.py
post_build: |
  from os import system, walk
  from shutil import copy2
  from pathlib import Path
  for file in Path("static").iterdir():
    cmd = f"ln -srf static/{file.name} ../public_html/{file.name}"
    print(cmd)
    system(cmd)
  for file in Path("static_kstg").iterdir():
    cmd = f"ln -srf static_kstg/{file.name} ../public_html/{file.name}"
    print(cmd)
    system(cmd)
  for (dir,_,_) in walk("static"):
    copy2("index.php",dir)