src_dir: src
out_dir: ../public_html
clear_ouput: True
global_args: {}
exclude_render:
- component/
- content/
- heste/
post_build: |
  from os import system
  from pathlib import Path
  for file in Path("static").iterdir():
    system(f"ln -srf static/{file.name} ../public_html/{file.name}")